/* r22: first-party restart-ticket store. Public code only; private ticket values
 * are generated by GAS and stored on this device, never uploaded to GitHub.
 * Only the configured GAS iframe with a per-navigation nonce can use this store.
 */
(function(){
  'use strict';
  const APP='iec-device-resume-v1', VERSION='2026.09.25-r22';
  const ROOT=new URL('./',location.href), frame=document.getElementById('boardFrame');
  if(!frame||window.top!==window||location.origin!=='https://yishiidenkikouji-alt.github.io'||ROOT.pathname!=='/iec-board-icon/board-pwa/')return;
  const state={nonce:'',page:'',source:null,origin:'',key:'',lastSeq:0,generation:0};
  function random(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');}
  function setStatus(text){const el=document.getElementById('entrySessionStatus');if(el)el.textContent=text;}
  function validTicket(value){return typeof value==='string'&&value.length<=2000&&/^iec-resume-v1\.[A-Za-z0-9_-]{50,1600}\.[A-Za-z0-9_-]{43}$/.test(value);}
  function read(){
    const text=localStorage.getItem(state.key);if(!text)return {revision:'',ticket:''};
    let data;try{data=JSON.parse(text);}catch(e){throw new Error('保存情報の形式を確認できません。管理者へ連絡してください。');}
    if(!data||data.v!==1||!/^[a-f0-9]{64}$/.test(data.revision)||!validTicket(data.ticket))throw new Error('保存情報の形式を確認できません。');
    return data;
  }
  function allowedOrigin(origin){return origin==='https://script.google.com'||/^https:\/\/(?:[a-z0-9-]+-)?script\.googleusercontent\.com$/.test(origin);}
  function belongs(source){
    try{for(let depth=0,cur=source;cur&&depth<10;depth++,cur=cur.parent){if(cur===frame.contentWindow)return true;if(cur===window||cur===cur.parent)return false;}}catch(e){}
    return false;
  }
  function reply(type,body){if(state.source)state.source.postMessage(Object.assign({app:APP,type:type,nonce:state.nonce,page:state.page},body||{}),state.origin);}
  function prepare(value){
    state.generation++;state.nonce='';state.page='';state.source=null;state.origin='';state.lastSeq=0;state.key='';
    let url;try{url=new URL(String(value));}catch(e){return value;}
    if(url.protocol!=='https:'||url.hostname!=='script.google.com'||url.username||url.password||url.port||!/^\/(?:a\/[^/]+\/)?macros\/s\/[A-Za-z0-9_-]{20,256}\/exec\/?$/.test(url.pathname))return value;
    state.nonce=random();
    state.key='iec.entry.resume.v1:'+ROOT.pathname+':'+url.origin+url.pathname.replace(/\/$/,'');
    // A short-lived channel nonce, NOT an identity or a login credential.
    url.searchParams.set('iec_resume_nonce',state.nonce);
    setStatus('端末保持 r22：GASとの連携を確認中…');return url.href;
  }
  // Only this application's iframe is wrapped. The existing badge code and
  // saved /exec URL remain unchanged; native src getter/setter do navigation.
  try{
    const descriptor=Object.getOwnPropertyDescriptor(HTMLIFrameElement.prototype,'src');
    if(!descriptor||!descriptor.get||!descriptor.set)throw new Error('src');
    Object.defineProperty(frame,'src',{configurable:true,get:function(){return descriptor.get.call(this);},set:function(value){descriptor.set.call(this,prepare(value));}});
  }catch(e){setStatus('端末保持を準備できませんでした。ブラウザーを確認してください。');return;}
  window.addEventListener('message',function(event){
    const d=event.data;
    if(!d||d.app!==APP||!state.nonce||d.nonce!==state.nonce||!/^[a-f0-9]{32}$/.test(String(d.page||''))||!allowedOrigin(event.origin)||!belongs(event.source))return;
    if(d.type==='hello'){
      if(state.source&&(state.source!==event.source||state.origin!==event.origin))return;
      if(state.page!==d.page)state.lastSeq=0;
      state.source=event.source;state.origin=event.origin;state.page=d.page;
      try{const saved=read();reply('ready',{revision:saved.revision,ticket:saved.ticket,version:VERSION});setStatus(saved.ticket?'端末保持 r22：保存した利用者をGASで検証中…':'端末保持 r22：未保存（GASで本人を登録後に保存します）');}
      catch(e){reply('ready',{revision:'',ticket:'',version:VERSION,error:'端末内の保存領域を読み取れません。'});setStatus('端末保持 r22：保存領域を利用できません');}
      return;
    }
    if(event.source!==state.source||event.origin!==state.origin||d.page!==state.page||!Number.isSafeInteger(d.seq)||d.seq<=state.lastSeq)return;
    state.lastSeq=d.seq;
    if(d.type!=='save'&&d.type!=='remove')return;
    const ack={requestId:String(d.requestId||''),ok:false};
    try{
      const old=read();
      if(typeof d.expectedRevision!=='string'||old.revision!==d.expectedRevision){ack.reason='conflict';throw new Error('別の画面で保存情報が変わりました。自動では上書きしません。');}
      if(d.type==='save'){
        if(!validTicket(d.ticket))throw new Error('復元情報の形式が不正です。');
        const saved={v:1,revision:random(),ticket:d.ticket};
        const text=JSON.stringify(saved);localStorage.setItem(state.key,text);
        if(localStorage.getItem(state.key)!==text)throw new Error('端末への保存を確認できません。');
        ack.revision=saved.revision;setStatus('端末保持 r22：この端末に保存確認済み');
      }else{
        localStorage.removeItem(state.key);
        if(localStorage.getItem(state.key)!==null)throw new Error('端末の保存解除を確認できません。');
        ack.revision='';setStatus('端末保持 r22：未保存');
      }
      ack.ok=true;
    }catch(e){ack.error=String(e&&e.message||'端末への保存に失敗しました。');if(!ack.reason)ack.reason='storage';}
    reply('ack',ack);
  });
  // Deliberately no transmission of tickets in URLs, logs, analytics, or fetch.
  const el=document.getElementById('entrySessionVersion');if(el)el.textContent=VERSION;
  setStatus('端末保持 r22：接続先の設定を待っています');
})();
